### ISSUE TITLE
Transdecoder.Predict

### ISSUE THREAD

**Issue by photocyte** [transXpress/transXpress-nextflow#1]
This step is missing from the Transdecoder predictions.  I think it is helpful & should be implemented, as it seems to improve the N-terminal prediction (trains an HMM that does it; perhaps it picks up on the Kozak sequence?)

**Comment by tomas-pluskal** [comment]
This has been added already. The pipeline now has two transdecoder processes, the second one is run after blast.

**Comment by photocyte** [comment]
For what it's worth, doesn't seem to be working off the bat with the current commit.  I'm currently running it without the blastp parameters of Transdecoder predict as a workaround.  Can investigate once the dag is produced to get a better sense for things.

```
transXpress now running. git hash: c8e97a5c66a8e6255e529799dd3c1f27284012a1
N E X T F L O W  ~  version 18.12.0-SNAPSHOT
Launching `transXpress.nf` [lethal_newton] - revision: b07b9e93c7

 transXpress
 ===================================
 Input samples file: samples.txt
 
[warm up] executor > lsf
ERROR ~ No such variable: blastpForTransdecoder

 -- Check script 'transXpress.nf' at line: 98 or see '.nextflow.log' file for more details
transXpress now running. git hash: c8e97a5c66a8e6255e529799dd3c1f27284012a1
N E X T F L O W  ~  version 18.12.0-SNAPSHOT
```

**Comment by tomas-pluskal** [comment]
Sorry, I reordered the processed before uploading to the repo, it was a mistake. Seems that nextFlow is sensitive to the order of the processes in the file (unlike make/snakemake). Channels have to be defined before they are used as inputs.

**Comment by tomas-pluskal** [comment]
Should be fixed now

**Comment by photocyte** [comment]
Does seem to be fixed.  

But from the current DAG (https://github.com/photocyte/transXpress/blob/master/tests/test_nonSS/test_nonSS_dag.html ; download and view in browser), it seems like the pfam / sprot_blastp / signalp / tmhmm results are calculated from the longorf.pep, but then later annotated onto the orfs from Transdecoder.Predict.  Is this a correct interpretation of the flow?  I believe the ORFs can change after Transdecoder.Predict, even if they have the same fasta record ID (which I presume they must for successful annotation of Transdecoder.Predict orfs with longorfs.pep derived searches).  This is relevant as Transdecoder.Predict does polishing of the N-terminus versus the longorfs.pep, and signalp / tmhmm are sensitive to the placement of the N-terminus, so the results may differ between longorfs.pep and Transdecoder.Predict peptides.

**Comment by tomas-pluskal** [comment]
True, we should move the signalp and tmhmm searches after the Transdecoder.Predict

**Comment by photocyte** [comment]
Handled in #9 .  Note: if the pfam or sprot_blastp results are reporting results w/ the coordinates of the orf, then they should be rerun of the Transdecoder. Predict orfs, as the orf coordinates may change between longorfs and Transdecoder.Predict orgs (could also try to liftover the coordinates instead of rerunning, if feeling bold)
