### ISSUE TITLE
samples.txt separator

### ISSUE THREAD

**Issue by tomas-pluskal** [transXpress/transXpress-nextflow#17]
https://github.com/transXpress/transXpress-nextflow/blob/506166713e488ae21b1a3bd38f0581356f6491a0/transXpress.nf#L129

I think the separator should be something like [ \t]+, people tend to make the samples.txt separated by spaces and as far as I know Trinity accepts that.

**Comment by photocyte** [comment]
That change seems to work directly:
0caa8e605e6e40b8261e276129898325d035c8ea

Will also review the convertSamplesToRelative process, as that probably makes some untenable assumptions about whitespace as well
