### ISSUE TITLE
Unique naming of produced transcripts / transcriptome files

### ISSUE THREAD

**Issue by photocyte** [transXpress/transXpress-nextflow#2]
I think it is good practice to label the transcriptome / transcripts with informative prefixes (e.g. date of calculation, species name, etc.) to make it easier to keep track of various assembly versions.

```
seqkit replace -r "^" "$DATE"
```

Is a suitable approach.

**Comment by tomas-pluskal** [comment]
Labeling each transcript seems to be an overkill, because the label would be the same for all transcripts.. no?

**Comment by photocyte** [comment]
The label would a shared assembly-unique identifier (e.g. SPECIES_DATE), plus the Trinity identifier. Labeling each transcript is the intent, as a given transcript without unique labeling can be easily separated from its parent transcriptome fasta file w/ unique labeling.  For example, by copy pasting the transcript FASTA record into a digital notebook, or serving multiple assemblies at the same time with sequenceserver.  In my experience if a transcript doesn't have unique labeling it gets quite hard to figure out where it came from.

**Comment by tomas-pluskal** [comment]
We can add a transcript id prefix as a parameter to the pipeline.
