### ISSUE TITLE
Initial downloading of Sprot seems to hang

### ISSUE THREAD

**Issue by photocyte** [transXpress/transXpress-nextflow#7]
(executing from modified ./run)
```
transXpress now running. git hash: c8e97a5c66a8e6255e529799dd3c1f27284012a1
N E X T F L O W  ~  version 18.12.0-SNAPSHOT
Launching `transXpress.nf` [compassionate_hodgkin] - revision: bcc492d3fd

 transXpress
 ===================================
 Input samples file: samples.txt
 
[warm up] executor > lsf
[8f/eefa37] Submitted process > trinityInchwormChrysalis
[f0/25a98a] Submitted process > downloadSprot
[98/7c23ff] Submitted process > downloadPfam
[f0/25a98a] NOTE: Missing output file(s) `uniprot_sprot.fasta` expected by process `downloadSprot` -- Execution is retried (1)
```
(Files seem to be there, is this a filesystem latency thing? I'm running the nextflow process on the cluster submission node, but the processes are presumably on the LSF cluster due to the config file)
```
[42/01f34b] Re-submitted process > downloadSprot
```
(process 42/01f34b seems to finish normally according to the exitcode / makeblastdb output, but nextflow is hanging?) Manually killed and restarted
```
transXpress now running. git hash: c8e97a5c66a8e6255e529799dd3c1f27284012a1
N E X T F L O W  ~  version 18.12.0-SNAPSHOT
Launching `transXpress.nf` [kickass_faggin] - revision: bcc492d3fd

 transXpress
 ===================================
 Input samples file: samples.txt
 
[warm up] executor > lsf
[skipping] Stored process > downloadPfam
[skipping] Stored process > downloadSprot
[da/d7ac29] Submitted process > trinityInchwormChrysalis
```
(Now seems to be working)

**Comment by tomas-pluskal** [comment]
That's the filesystem latency issue. The nextFlow developer seems to be of the opinion that this is a sign of misconfiguration of our cluster filesystem (i.e., not a nextFlow problem).

**Comment by photocyte** [comment]
Which nextflow issue is this?  I'll follow up there

**Comment by tomas-pluskal** [comment]
https://github.com/nextflow-io/nextflow/issues/931

**Comment by photocyte** [comment]
Added some sleep statements here and there to processes that have a very long runtime (so the impact of the added sleep statement should be minimal).  Alternatively, the automatic retry on fail function within nextflow does recover from this, although it is not ideal or a good use of computational time.
